MACOSX_SDK_VERSION:        # [osx]
  - '12.3'                 # [osx]
c_stdlib:
  - sysroot                    # [linux]
c_stdlib_version:              # [unix]
  - 2.17                       # [linux and x86_64]
