{% set name = "qcachegrind" %}
{% set version = "0.7.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://sourceforge.net/projects/kcachegrind/files/kcachegrind-{{ version }}.tar.gz
  sha256: 0bf6efb647d500bf09bbbab617d30a8a2a0a2cbf87fd1f2a1375d774c005b379
  patches:
    - add-qobject-header.patch

build:
  number: 0
  skip: True  # [ppc64le]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxext') }}     # [linux]
    - sysroot_linux-64 2.17    # [linux and x86_64]
    - jom       # [win]
    - m2-patch  # [win]
    - automake  # [unix]
    - make      # [not win]
    - patch     # [not win]
  host:
    - xorg-libxfixes  # [linux]
    - qt-main


test:
  commands:
    - test -f ${PREFIX}/bin/cgview       # [unix]
    - test -f ${PREFIX}/bin/qcachegrind  # [unix]
    - if not exist %LIBRARY_BIN%\cgview.exe exit 1       # [win]
    - if not exist %LIBRARY_BIN%\qcachegrind.exe exit 1  # [win]

about:
  home: http://kcachegrind.sourceforge.net/html/Home.html
  license: GPL-2.0-only
  license_family: GPL
  license_file: COPYING
  summary: A profiling data visualizer
  description: |
    This tool allows visualisation of profiling data in the callgrind-format.
  doc_url: http://kcachegrind.sourceforge.net/html/Documentation.html
  doc_source_url: https://github.com/kcachegrind/kcachegrind.github.io/blob/master/html
  dev_url: https://sourceforge.net/projects/kcachegrind

extra:
  recipe-maintainers:
    - timkpaine
